- hosts: localhost
  become: true
  pre_tasks:
          - name: Update repositories
            apt:
              update_cache=yes
              cache_valid_time=3600
            changed_when: False


  tasks:
          - include: tasks/install_packages.yml
          - include: tasks/pip_packages.yml
          - include: tasks/firefox_local_js.yml
          - include: tasks/thonny_desktop_file_uninstall.yml
          - include: tasks/firefox_policy.yml
          - include: tasks/users.yml
          - include: tasks/temp_user.yml
          - include: tasks/cron.yml
          - include: tasks/iptables_blacklist.yml
          - include: tasks/iptables_rules_v4.yml
          - include: tasks/iptables-persistent-run.yml
          - include: tasks/update_pam_lightdm.yml
          - include: tasks/manage_systemd.yml
          - include: tasks/update_systemd_logind_conf.yml
