- hosts: localhost
  become: true
  pre_tasks:
          - name: Update repositories
            apt:
              update_cache=yes
              cache_valid_time=3600
            changed_when: False


  tasks:
          - include:
              tasks/install_packages.yml 
              tasks/users.yml
              tasks/cron.yml
              tasks/iptables_blacklist.yml
