- hosts: localhost
  become: true
  pre_tasks:
          - name: Update repositories
            apt:
              update_cache=yes
              cache_valid_time=3600
            changed_when: False


  tasks:
          - include: tasks/install_packages.yml
          - include: tasks/users.yml
          - include: tasks/cron.yml
          - include: tasks/iptables_blacklist.yml
