- name: disable some systemd system units
  systemd:
          name: "{{ item }}"
          state: stopped
          enabled: no
  with_items:
          - 'kerneloops.service'
          - 'ModemManager.service'
          - 'whoopsie.service'
          - 'avahi-daemon.service'
          - 'avahi-daemon.socket'
